# 100 numpy exercises

###Drew Honson

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.version.version)
print(np.__config__)

1.12.1
<module 'numpy.__config__' from '/Users/honsondd/anaconda/lib/python3.6/site-packages/numpy/__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
ten_zeroes = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [9]:
ten_zeroes.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y, ou

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
ten_zeroes[4] = 1
print(ten_zeroes)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [25]:
ten_fortynine_flip = np.flip(ten_fortynine, 0)
print(ten_fortynine_flip)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
threexthree = np.arange(9).reshape(3,3)
print(threexthree)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [3]:
import numpy as np
nz_elem = np.array([1,2,0,0,4,0])
nz_index = []
for i,v in enumerate(nz_elem):
    if v != 0:
        nz_index.append(i)
print(nz_index)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [6]:
id_matrix = np.eye(3)
print(id_matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [6]:
import numpy as np
twentyseven = np.random.randint(0, 100, (3,3,3))
print(twentyseven)

[[[ 4 40 39]
  [82 98 27]
  [79 31 80]]

 [[51 36 29]
  [39  6 10]
  [ 6 25 14]]

 [[88 78 81]
  [48 26 11]
  [81 54 91]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [8]:
one_hunnid = np.random.randint(0,100,(10,10))
print(one_hunnid)
print("Maximum Value:  " + str(one_hunnid.max()))
print("Minimum Value:  " + str(one_hunnid.min()))

[[82 55 53 31 50 45 78 23 75 48]
 [33 42 96 57 48  1 45  0 87 39]
 [92 36 74 51 15 44 43 91 93 21]
 [65 89 95 43 95 45 55 94 53 47]
 [69 68 66 27 42 29  0 71 47 40]
 [ 4 70  5 54 70 52  1 90  9  4]
 [15 95 82  9 44 93 91 39 90 78]
 [30 87 87  0 66  2 83 84 44 45]
 [ 8 53 59 92 19 49 19 68 58 57]
 [87 22 78 55  5 46 42 33 68  2]]
Maximum Value:  96
Minimum Value:  0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [9]:
thirty = np.random.randint(0,100,30)
print(thirty)
print(thirty.mean())

[26 82 94 94 58 90 73 35  9 21 20 67 27 82 66 97 24 65  9 93 27  2 80 15 71
 37 97 32 31 85]
53.6333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [14]:
import numpy as np
zero_border = np.ones((10,10))
print(zero_border)
bordered = np.pad(zero_border, (1,1), mode = 'constant')
print(bordered)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
onetwothreefour = np.zeros((5,5))
onetwothreefour[1,0] = 1
onetwothreefour[2,1] = 2
onetwothreefour[3,2] = 3
onetwothreefour[4,3] = 4
print(onetwothreefour)

[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
checkerboard = np.zeros((8,8))
print(checkerboard)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [7]:
import numpy as np
seven_ate_nine = np.random.randint(1,100,(6,7,8))
print(seven_ate_nine)
seven_ate_nine[1,5,3] #100th element

[[[76 79 86 35 11 49 89 48]
  [30 66 93 73 17  1 66 14]
  [43 22 74 19 71  1 25 94]
  [84 88 41 83 30 39  4 44]
  [86 68 63 12 91 89  9 54]
  [68 26 61 93 65 50 31 97]
  [65 30 32 21 68 29 48 86]]

 [[97 61  5 22 75  5 60 66]
  [79 12 18 39 65 56 68 39]
  [32 17 37 57 97 78 41 91]
  [90  3 24 33 48 85 26  5]
  [11 66 85 68  6 49 76 37]
  [92 67 39 75 24 98 53 94]
  [69  8 55  6 38 57 21 80]]

 [[11 72 20 94 26 90 13 81]
  [95 51 65 66 51 59 10 75]
  [20 48 44 28 53 13 22 14]
  [67 44 84 46 67 95 56 38]
  [72 98 41 32 18 82 47 59]
  [97 87  2  5 27 10 71 62]
  [43 98 20 80 52 84 56  3]]

 [[32 68 24  4  2 83 11 35]
  [99 63 74 41 68  3 92 68]
  [26 96 40 43 94 46 69 40]
  [31 36 37 54 93  1 87 29]
  [90 40 86 28 15 53 88 56]
  [98 71  7 30 83 96 42 45]
  [15 52 26  4 49  3 17 82]]

 [[90 97 41 67 91 88 80  4]
  [39 94 63 75 67 82 42 89]
  [58 33 96 80 97 52 84 70]
  [17 10 34 69  1 84 56 65]
  [85 17 45 64 42 18 46  4]
  [68 27 33  7 50 71 97 24]
  [57 47  9 49 54 63 35 79]]

 [[44 51 7

75

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [12]:
checks = np.array([0,1])
board = np.tile(checks,(8,4))
print(board)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
abnormal = np.random.random((5,5))
print("Not Normalized: ")
print(abnormal)
normal = (abnormal - abnormal.min())/(abnormal.max()-abnormal.min())
print("Normalized: ")
print(normal)

Not Normalized: 
[[ 0.29101465  0.03109698  0.48079219  0.38226806  0.07674011]
 [ 0.13436194  0.67429428  0.20478764  0.97378113  0.12173363]
 [ 0.4077673   0.19843617  0.66182368  0.65812422  0.39475887]
 [ 0.56228611  0.13573806  0.77670098  0.06888246  0.07412236]
 [ 0.90989984  0.79911466  0.48333001  0.92815356  0.99777774]]
Normalized: 
[[ 0.26887643  0.          0.46519516  0.36327513  0.04721635]
 [ 0.10682426  0.66536681  0.17967737  0.97517628  0.09376068]
 [ 0.38965327  0.17310698  0.65246639  0.64863941  0.37619647]
 [ 0.54949799  0.10824781  0.77130323  0.03908786  0.04450836]
 [ 0.90909315  0.79448947  0.46782045  0.92797604  1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [20]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(type(color))
print(color)

<class 'numpy.dtype'>
[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
np.random.seed(42)
fivethree = np.random.randint(1,10,(5,3))
threetwo = np.random.randint(1,10,(3,2))
multiply = np.dot(fivethree, threetwo)
print("5x3 Matrix")
print(fivethree)
print("3x2 Matrix")
print(threetwo)
print("Real Matrix Product") 
print(multiply)

5x3 Matrix
[[7 4 8]
 [5 7 3]
 [7 8 5]
 [4 8 8]
 [3 6 5]]
3x2 Matrix
[[2 8]
 [6 2]
 [5 1]]
Real Matrix Product
[[78 72]
 [67 57]
 [87 77]
 [96 56]
 [67 41]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
np.random.seed(1)
oneD = np.array([1,2,3,4,5,6,7,8,9,10])
print("Before: ")
print(oneD)
oneD[(3 < oneD) & (oneD < 9)] *= -1
print("After: ")
print(oneD)

Before: 
[ 1  2  3  4  5  6  7  8  9 10]
After: 
[ 1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5),-1))
#1 + 2 + 3 + 4 - 1 = 9
from numpy import * # Imports every numpy module
print(sum(range(5),-1)) # Some numpy module changes the interpretation of this

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [59]:
# All are valid except Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
np.array(0) / np.array(0) #Error
np.array(0) // np.array(0) #Error but also prints 0
np.array([np.nan]).astype(int).astype(float) #Value below

array([ -9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [101]:
randos = np.random.uniform(0,10,10)
print(randos)
print(np.ceil(randos))

[ 5.92414569  0.46450413  6.07544852  1.70524124  0.65051593  9.48885537
  9.65632033  8.08397348  3.04613769  0.97672114]
[  6.   1.   7.   2.   1.  10.  10.   9.   4.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [72]:
a1 = np.arange(25)
print("Array 1")
print(a1)
a2 = np.arange(10,51)
print("Array 2")
print(a2)
a3 = np.intersect1d(a1,a2)
print("Common Values")
print(a3)

Array 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Array 2
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Common Values
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all = 'ignore') #I'm not going to run this

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [74]:
# No

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [80]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2017-11-16
2017-11-17
2017-11-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [82]:
july16 = np.arange('2016-07','2016-08', dtype = 'datetime64[D]')
print(july16)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [97]:
np.random.seed(42)
A = np.random.randint(1,20,10)
print(A)
B = np.random.randint(21,50,10)
print(B)
np.add(A, B, out = B)
np.divide(A, -2, out = A, casting = 'unsafe')
np.multiply(A,B, out = B)

[ 7 15 11  8  7 19 11 11  4  8]
[44 23 42 41 22 44 32 26 22 48]


array([-153, -266, -265, -196,  -87, -567, -215, -185,  -52, -224])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [121]:
np.random.seed(42)
rand = np.random.uniform(0,10,5)

print(rand)

print(np.ceil(rand)-1)
print(np.floor(rand))
print(np.trunc(rand))
print(rand.astype('int'))
print(rand - rand%1)

[ 3.74540119  9.50714306  7.31993942  5.98658484  1.5601864 ]
[ 3.  9.  7.  5.  1.]
[ 3.  9.  7.  5.  1.]
[ 3.  9.  7.  5.  1.]
[3 9 7 5 1]
[ 3.  9.  7.  5.  1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [128]:
matrix = np.zeros((5,5))
print(matrix)
matrix += np.arange(5)
print(matrix)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [131]:
def generator():
    global tenintegers 
    tenintegers = np.array(np.arange(10))
generator()
print(tenintegers)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [132]:
print(np.linspace(0,1,num = 10, endpoint = False))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [137]:
np.random.seed(42)
vector = np.random.random(10)
print("Unsorted")
print(vector)
print("Sorted")
vector.sort()
print(vector)

Unsorted
[ 0.37454012  0.95071431  0.73199394  0.59865848  0.15601864  0.15599452
  0.05808361  0.86617615  0.60111501  0.70807258]
Sorted
[ 0.05808361  0.15599452  0.15601864  0.37454012  0.59865848  0.60111501
  0.70807258  0.73199394  0.86617615  0.95071431]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [139]:
small = np.arange(10)

import timeit
timeit.timeit(np.sum(small), number = 10000)


ValueError: stmt is neither a string nor callable

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)